services:
  app:
    image: node
    command: sh -c "npm install && npm run dev"
    ports:
      - 127.0.0.1:4000:4000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MONGODB_URL: mongodb://mongo:27017/graphqldemo
  mongo:
    image: mongo